# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/FOSWLY/vot-worker"
description = ""
language = "javascript"
manifest_version = 3
name = "vot-worker"
service_id = ""

[scripts]
build = "npm run build"
post_init = "npm install"
